"""author_uc

Revision ID: 7851904c7852
Revises: e0aaaf4ce6c5
Create Date: 2023-02-10 18:27:50.243209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7851904c7852'
down_revision = 'e0aaaf4ce6c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_proposal_author_uc', 'authors', ['proposal_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_proposal_author_uc', 'authors', type_='unique')
    # ### end Alembic commands ###
