"""created_at

Revision ID: dc6d73f1790f
Revises: 7851904c7852
Create Date: 2023-02-12 12:25:03.123853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc6d73f1790f'
down_revision = '7851904c7852'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('proposals', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('verifications', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('verifications', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifications', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('verifications', 'verified_at')
    op.drop_column('users', 'registered_at')
    op.drop_column('proposals', 'created_at')
    op.drop_column('authors', 'created_at')
    # ### end Alembic commands ###
